version: "3.7"
services:
  backend:
    build: ./backend
    tty: true
    ports:
      - 3001:3001
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mongo:7.0-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    depends_on:
      - backend
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
